name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest
    outputs:
      scripts: ${{ steps.scripts.outputs.scripts }}
    steps:
      - uses: actions/checkout@v4
      - name: Define scripts
        id: scripts
        run: |
          echo "scripts=[\"$(find scripts -type f | xargs | sed 's/ /", "/g')\"]" >> "$GITHUB_OUTPUT"

  execute:
    runs-on: ubuntu-latest
    needs: list
    name: "${{ matrix.script }}"
    strategy:
      matrix:
        script: ${{ fromJSON(needs.list.outputs.scripts) }}
    steps:
      - uses: actions/checkout@v4
      - run: ${{ matrix.script }}
