name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  works:
    runs-on: ubuntu-latest
    name: "{{ matrix.script }}"
    strategy:
      matrix:
        script: ["works.sh", "fails.sh", "waits.sh"]
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/${{ matrix.script }}
